---
# tasks file for kfieldho.influx
#

- name: Install Shairport Apt Dependencies
  become: True
  become_user: root
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
      - build-essential
      - git
      - xmltoman
      - autoconf
      - automake
      - libtool
      - libdaemon-dev
      - libpopt-dev
      - libconfig-dev
      - libasound2-dev
      - avahi-daemon
      - libavahi-client-dev
      - libssl-dev

- name: Fetch Shairport Git Repo
  git:
    repo: "{{ shairport_sync_repo }}"
    dest: "{{ ansible_env.HOME }}/shairport-sync"
    version: "{{ shairport_sync_version }}"

- name: Pre-configure Shairport Sync
  command: autoreconf -i -f
  args:
    chdir: "{{ ansible_env.HOME }}/shairport-sync"
    creates: "{{ ansible_env.HOME }}/shairport-sync/INSTALL"

- name: Configure Shairport Sync
  command: ./configure --with-configfiles --with-avahi --with-alsa --with-ssl=openssl --with-systemd
  args:
    chdir: "{{ ansible_env.HOME }}/shairport-sync"
    creates: "{{ ansible_env.HOME }}/shairport-sync/config.log"

- name: Build Shairport Sync
  make:
  args:
    chdir: "{{ ansible_env.HOME }}/shairport-sync"

- name: Install Shairport Sync
  become: True
  become_user: root
  make:
  args:
    chdir: "{{ ansible_env.HOME }}/shairport-sync"
    target: install

- name: Install Shairport Configuration
  become: True
  become_user: root
  template:
  args:
    src: shairport-conf.j2
    dest: /usr/local/etc/shairport-sync.conf
    force: yes

- name: Enable Shairport Sync Service
  become: True
  become_user: root
  systemd: name=shairport-sync.service enabled=true state=started daemon_reload=true
